name: Feature Request
description: Request a new feature for the platform
title: "[EPIC-XXX]: "
labels: ["type:feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request Template
        Please fill out all sections to help agents understand and implement this feature.

  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: Describe the feature clearly
      placeholder: What should be implemented?
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tareas
      description: Break down into specific tasks
      value: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Criterios de Aceptación
      description: Define what success looks like
      value: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: dropdown
    id: primary-agent
    attributes:
      label: Agente Principal
      description: Which agent should implement this?
      options:
        - api-developer
        - frontend-developer
        - game-developer
        - devops-engineer
        - testing-engineer
    validations:
      required: true

  - type: dropdown
    id: secondary-agent
    attributes:
      label: Agente Secundario
      description: Optional secondary agent for review or support
      options:
        - none
        - api-developer
        - frontend-developer
        - game-developer
        - devops-engineer
        - testing-engineer
        - code-reviewer

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencias
      description: List any blocking issues
      placeholder: "Bloqueado por: #XX"

  - type: dropdown
    id: complexity
    attributes:
      label: Complejidad
      description: Estimated effort
      options:
        - S (2h)
        - M (4h)
        - L (8h)
        - XL (16h+)
    validations:
      required: true
